 #    parameter_name: value
 
 services:
+    _defaults:
+        autowire: true
+        autoconfigure: true
+        public: false
+        
     web_service:
         class: ShopBundle\WebService\WebService
         arguments: [entityManager, 1000, 1000]