## Page 1 Form 1 -> form for Reservation entity
oc_shop_visitorform:
    path:     /tickets/info
    defaults: { _controller: OCShopBundle:Booking:visitorForm }
    methods: [POST,GET]



## Page 2 -> choose your TICKET
oc_shop_homepage:
    path:     /ticket
    defaults: { _controller: OCShopBundle:Booking:add }
    methods: [POST,GET]





## Form 3 -> PAYMENT
oc_shop_payment:
    path:     /tickets/payment
    defaults: { _controller: OCShopBundle:Booking:payment }
    methods: [POST,GET]